import type { FlowbiteTheme } from "../src/components/Flowbite";
import { accordionTheme } from "./components/Accordion/theme";
import type { DeepPartial } from "../src/types";

export type CustomFlowbiteTheme = DeepPartial<FlowbiteTheme>;

export const theme: FlowbiteTheme = {
  accordion: accordionTheme,
  alert: undefined,
  avatar: undefined,
  badge: undefined,
  blockquote: undefined,
  breadcrumb: undefined,
  button: undefined,
  buttonGroup: undefined,
  card: undefined,
  carousel: undefined,
  checkbox: undefined,
  clipboard: undefined,
  darkThemeToggle: undefined,
  datepicker: undefined,
  drawer: undefined,
  dropdown: undefined,
  fileInput: undefined,
  floatingLabel: undefined,
  footer: undefined,
  helperText: undefined,
  hr: undefined,
  kbd: undefined,
  label: undefined,
  list: undefined,
  listGroup: undefined,
  megaMenu: undefined,
  modal: undefined,
  navbar: undefined,
  pagination: undefined,
  popover: undefined,
  progress: undefined,
  radio: undefined,
  rangeSlider: undefined,
  rating: undefined,
  ratingAdvanced: undefined,
  select: undefined,
  sidebar: undefined,
  spinner: undefined,
  table: undefined,
  tabs: undefined,
  textarea: undefined,
  textInput: undefined,
  timeline: undefined,
  toast: undefined,
  toggleSwitch: undefined,
  tooltip: undefined
};
